package com.craftinginterpreters.lox.interpreter;

/**
 * Generated by GenerateAst.java class
 */

public abstract class Stmt {
    interface Visitor<R> {
        R visitExpressionStmt(Expression stmt);

        R visitPrintStmt(Print stmt);
    }

    /**
     * exprStmt  → expression ";" ;
     */
    public static class Expression extends Stmt {
        public Expression(Expr expression) {
            this.expression = expression;
        }

        <R> R accept(Visitor<R> visitor) {
            return visitor.visitExpressionStmt(this);
        }

        final Expr expression;
    }

    /**
     * printStmt → "print" expression ";" ;
     */
    public static class Print extends Stmt {
        public Print(Expr expression) {
            this.expression = expression;
        }

        <R> R accept(Visitor<R> visitor) {
            return visitor.visitPrintStmt(this);
        }

        final Expr expression;
    }

    abstract <R> R accept(Visitor<R> visitor);
}
